[package]
name = "gen-semver-tags"
version = "0.1.0"
edition = "2021"

[lib]
name = "gen_semver_tags"
path = "src/lib.rs"

[[bin]]
name = "gen-semver-tags"
path = "src/main.rs"

[dependencies]
semver = "1.0.25"
